ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_1024(
  'snowflake-arctic-embed-l-v2.0',
  'This is a test sentence to verify the embedding model works.'
) AS embedding;

SHOW PARAMETERS IN ACCOUNT;
SELECT *
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "key" like '%CORTEX%';

select * from SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY;

USE ROLE SECURITYADMIN;
drop ROLE RA_DB_DEPLOY;
GRANT ROLE RA_DB_DEPLOY TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
drop DATABASE DB;
GRANT OWNERSHIP ON DATABASE DB TO ROLE RA_DB_DEPLOY;

SHOW GRANTS ON DATABASE DB;
SHOW GRANTS ON SCHEMA DB.PUBLIC;


ALTER API INTEGRATION API_INTEGRATION_GIT_REPOSITORY
  SET ALLOWED_AUTHENTICATION_SECRETS = ("USER$ARUIZ".PUBLIC.GIT_SECRET);

drop secret "USER$ARUIZ".PUBLIC.GIT_SECRET2;

  