USE ROLE ACCOUNTADMIN;
CREATE SECURITY INTEGRATION POC_MCP_OAUTH
  TYPE = OAUTH
  OAUTH_CLIENT = CUSTOM
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_ISSUE_REFRESH_TOKENS = TRUE
  OAUTH_REDIRECT_URI = 'https://claude.ai/api/mcp/auth_callback'
  OAUTH_REFRESH_TOKEN_VALIDITY = 7776000
  OAUTH_SINGLE_USE_REFRESH_TOKENS_REQUIRED = FALSE
  OAUTH_USE_SECONDARY_ROLES = 'IMPLICIT'
  PRE_AUTHORIZED_ROLES_LIST = ()
  BLOCKED_ROLES_LIST = ('ACCOUNTADMIN', 'SECURITYADMIN', 'SYSADMIN', 'USERADMIN')
  OAUTH_ALLOW_NON_TLS_REDIRECT_URI = FALSE
  OAUTH_ENFORCE_PKCE = FALSE
  ENABLED = TRUE;


BEGIN
USE DATABASE EVT_PRIV_TEST_DB;
SELECT CURRENT_DATABASE(),CURRENT_DATE();
END;

SHOW PARAMETERS IN ACCOUNT;

show grants TO ROLE PUBLIC;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO PUBLIC;
SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;

SHOW GRANTS ON ACCOUNT;

SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;

SELECT SNOWFLAKE.CORTEX.COMPLETE('claude-4', 'say hello');

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE = 'AI_SERVICES'
ORDER BY START_TIME DESC;

SELECT * FROM SNOWFLAKE.ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY
ORDER BY DATE DESC ;

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
ORDER BY USAGE_TIME DESC;

SHOW PARAMETERS LIKE '%CORTEX%' IN ACCOUNT;

SHOW GRANTS OF DATABASE ROLE SNOWFLAKE.CORTEX_USER;

SELECT SYSTEM$ACCEPT_LEGAL_TERMS('...'); -- terms name varies, usually surfaced via UI prompt
SELECT SNOWFLAKE.CORTEX.COMPLETE('claude-4', 'say hello');