USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE DATABASE SNOWFLAKE_HIS;
CREATE SCHEMA SNOWFLAKE_HIS.ACCOUNT_USAGE;

CALL USER_ADM_DB.PUBLIC.SP_INCREMENTAL_COPY(
        'SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY',
    'SNOWFLAKE_HIS.ACCOUNT_USAGE.QUERY_HISTORY',
    'END_TIME'
);

select count(*)
from SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;

select *
from SNOWFLAKE_HIS.ACCOUNT_USAGE.QUERY_HISTORY
order by START_TIME desc;

describe table SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;

use role ACCOUNTADMIN;
select *
from SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY;

show views in SNOWFLAKE.ACCOUNT_USAGE;

describe table SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;


-----------------------------------------------

CREATE OR REPLACE CATALOG INTEGRATION CATALOG_DATABRICKS_ICEBERG_TEST
  CATALOG_SOURCE = ICEBERG_REST
  TABLE_FORMAT = ICEBERG
  CATALOG_NAMESPACE = 'test_iceberg' --
  REST_CONFIG = (
    CATALOG_URI = 'https://dbc-85db9a55-7c00.cloud.databricks.com/api/2.1/unity-catalog/iceberg-rest/'
    CATALOG_NAME = 'test_iceberg' --
    ACCESS_DELEGATION_MODE = VENDED_CREDENTIALS
  )
  REST_AUTHENTICATION = (
    TYPE = OAUTH
    OAUTH_TOKEN_URI = 'https://dbc-85db9a55-7c00.cloud.databricks.com/oidc/v1/token'
    OAUTH_CLIENT_ID = '307d4f26-ed66-4d85-99a7-4f0c72e9a628'
    OAUTH_CLIENT_SECRET = 'dosed2f5d2e44ce65ce9c14e2981536caa84'
    OAUTH_ALLOWED_SCOPES = ('all-apis', 'sql')
  )
  ENABLED = TRUE
  REFRESH_INTERVAL_SECONDS = 30;

DROP DATABASE POC_DATABRICKS_ICEBERG_TEST;
CREATE DATABASE POC_DATABRICKS_ICEBERG_TEST
  LINKED_CATALOG = ( CATALOG = CATALOG_DATABRICKS_ICEBERG_TEST );

SHOW DATABASES;
SHOW SCHEMAS IN DATABASE POC_DATABRICKS_ICEBERG_TEST;
SHOW TABLES IN SCHEMA POC_DATABRICKS_ICEBERG_TEST."demo";

SELECT *
FROM POC_DATABRICKS_ICEBERG_TEST."demo"."tbl_iceberg";