CREATE OR REPLACE SECRET SECRET_GIT_GIT_REPOSITORY_SNOWFLAKE
  TYPE = password
  USERNAME = 'GitHub username'
  PASSWORD = 'Personal access tokens (classic)';

CREATE OR REPLACE API INTEGRATION API_INTEGRATION_GIT_REPOSITORY_SNOWFLAKE
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/aldoruizw/snowflake.git')
  ALLOWED_AUTHENTICATION_SECRETS = (SECRET_GIT_REPOSITORY_SNOWFLAKE)
  ENABLED = TRUE;
