SELECT LOWER(current_organization_name()) as your_org_name, LOWER(current_account_name()) as your_account_name;
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();

SELECT CURRENT_ORGANIZATION_NAME() AS ORG, 
       CURRENT_ACCOUNT_NAME() AS ACC,
       CURRENT_REGION() AS REG;

USE ROLE SECURITYADMIN;
CREATE USER SVC_TERRAFORM
    TYPE = SERVICE
    COMMENT = "Service user for Terraform Snowflake"
    --RSA_PUBLIC_KEY = "<RSA_PUBLIC_KEY_HERE>"
    RSA_PUBLIC_KEY = '...'
;

ALTER USER SVC_TERRAFORM SET RSA_PUBLIC_KEY='...';

USE ROLE SECURITYADMIN;

GRANT ROLE SYSADMIN TO USER SVC_TERRAFORM;
GRANT ROLE SECURITYADMIN TO USER SVC_TERRAFORM;

USE ROLE ACCOUNTADMIN;

DESC USER SVC_TERRAFORM
  ->> SELECT SUBSTR(
        (SELECT "value" FROM $1
           WHERE "property" = 'RSA_PUBLIC_KEY_FP'),
        LEN('SHA256:') + 1) AS key;