CREATE OR REPLACE SECRET SECRET_GIT_REPOSITORY_SNOWFLAKE
  TYPE = password
  USERNAME = 'GitHub username'
  PASSWOReD = 'Personal access tokens (classic)';

CREATE OR REPLACE API INTEGRATION API_INTEGRATION_GIT_REPOSITORY
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/aldoruizw/snowflake.git')
  API_USER_AUTHENTICATION = (TYPE = SNOWFLAKE_GITHUB_APP)
  ENABLED = TRUE;