use role SYSADMIN;
create database if not exists HOW_TO_ANALYTICS_DEV;
create database if not exists HOW_TO_ANALYTICS_PROD;
create database if not exists HOW_TO_ANALYTICS_RAW;
create database if not exists HOW_TO_ANALYTICS_TEST;
create database if not exists RAW;
create warehouse if not exists HOW_TO_ANALYTICS_PROD_WH with warehouse_size = 'XSMALL';

use role SECURITYADMIN;
create role if not exists HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;

--BEGIN PROD
use role SYSADMIN;
--1. Database-level privileges
GRANT ALL PRIVILEGES                        ON DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
--2. Schema-level privileges (existing schemas)
GRANT ALL PRIVILEGES ON ALL SCHEMAS         IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
--3. Schema-level privileges (future schemas)
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS      IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
--4. Object-level privileges inside schemas
--Existing objects
GRANT ALL PRIVILEGES ON ALL TABLES          IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS           IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL STAGES          IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS    IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL SEQUENCES       IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS       IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL PROCEDURES      IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL STREAMS         IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON ALL TASKS           IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
--Future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES       IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS        IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES       IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES    IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS    IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES   IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS      IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS        IN DATABASE HOW_TO_ANALYTICS_PROD TO ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;
--END PROD

use role SYSADMIN;
grant usage on warehouse HOW_TO_ANALYTICS_PROD_WH to role HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE;

// prod service account
use role USERADMIN;
CREATE USER HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_USER
PASSWORD = 'da7579ee-2922-47c0-bf1d-841494bb8ef01A'
COMMENT = 'Service account for dbt in the production (PROD) environment of the how_to_analytics project.'
DEFAULT_WAREHOUSE = HOW_TO_ANALYTICS_PROD_WH
DEFAULT_ROLE = HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE
MUST_CHANGE_PASSWORD = FALSE;
// grant permissions to service accounts
--GRANT ROLE HOW_TO_ANALYTICS_DBT_TEST_SERVICE_ACCOUNT_ROLE TO USER how_to_analytics_DBT_TEST_SERVICE_ACCOUNT_USER;
GRANT ROLE HOW_TO_ANALYTICS_DBT_PROD_SERVICE_ACCOUNT_ROLE TO USER how_to_analytics_DBT_PROD_SERVICE_ACCOUNT_USER;
